import = ["~/.config/alacritty/themes/alacritty-theme/themes/one_dark.toml"]

live_config_reload = true

[font]
size = 14
normal = { family = "Hack Nerd Font", style = "Regular" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/local/bin/fish"
args = ["--login", "--command", "zellij"]

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

# Key bindings

[mouse]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 15000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
