" Generated by vim-plug
" Wed Jul 10 10:26:30 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['cppinsights.vim'].commit = '4cc9c5556566e40cf21008b7aeba95ec211d6bb7'
silent! let g:plugs['csharpls-extended-lsp.nvim'].commit = '5a474b06743bb20a90191994457f5e62f444976b'
silent! let g:plugs['diffview.nvim'].commit = '4516612fe98ff56ae0415a259ff6361a89419b0a'
silent! let g:plugs['fzf'].commit = '9e92b6f11e0f59272de410f56493893334071e6e'
silent! let g:plugs['fzf.vim'].commit = '279e1ec068f526e985ee7e3f62a71f083bbe0196'
silent! let g:plugs['godbolt.nvim'].commit = '777a454e310a6b03c498727449eff3caabd70fa1'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['lualine.nvim'].commit = '6a40b530539d2209f7dc0492f3681c8c126647ad'
silent! let g:plugs['nerdtree'].commit = 'fbb71fcd90602e3ec77f40b864b5f9b437c496c5'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['none-ls-extras.nvim'].commit = 'ac3b973aa3fabddcb59a493570c63f913ebdb821'
silent! let g:plugs['none-ls.nvim'].commit = '0d1b3fa2ad0b371b94cb4b9a27ba6e5a1a915c91'
silent! let g:plugs['nvim-autopairs'].commit = '78a4507bb9ffc9b00f11ae0ac48243d00cb9194d'
silent! let g:plugs['nvim-cmp'].commit = 'a110e12d0b58eefcf5b771f533fc2cf3050680ac'
silent! let g:plugs['nvim-echo-diagnostics'].commit = 'a8f82151b1789e532253f4a6155dd2dac4653a81'
silent! let g:plugs['nvim-lspconfig'].commit = 'cf97d2485fc3f6d4df1b79a3ea183e24c272215e'
silent! let g:plugs['nvim-treesitter'].commit = 'c1ad655b6a0c83ab48e55240f367e2bc0c15af31'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['plenary.nvim'].commit = 'a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683'
silent! let g:plugs['sig-window-nvim'].commit = '606e9dbd1f80646c8d2d1b4384872ec718ddc48a'
silent! let g:plugs['targets.vim'].commit = '642d3a4ce306264b05ea3219920b13ea80931767'
silent! let g:plugs['vim-cppman'].commit = '1fe11060f5bfc72d20f2c928dd3c06a309db50fc'
silent! let g:plugs['vim-fugitive'].commit = '8c8cdf4405cb8bdb70dd9812a33bb52363a87dbc'
silent! let g:plugs['vim-macroeditor'].commit = '25fd58a712f58ed16ebe924c4f92c9999e455e95'
silent! let g:plugs['vim-signify'].commit = '8670143f9e12ed1cd3c9b2c54f345cdd9a4baac3'
silent! let g:plugs['vim-skip'].commit = '891a7af8d16fea5a1aa3aed55414686c01820673'
silent! let g:plugs['vim-visual-multi'].commit = '38b0e8d94a5499ccc17d6159763d32c79f53417b'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['zoomwintab.vim'].commit = '3b76f740534ecc4114bc8a207ecb0db77b2fb002'

PlugUpdate!

