" Generated by vim-plug
" Mon May 20 18:31:40 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['csharpls-extended-lsp.nvim'].commit = 'bde4aebe0dc74952188c2130c6831a1d8e4ce5c6'
silent! let g:plugs['diffview.nvim'].commit = '9bdd5537575c2ea7925b71ae06585b934beea13d'
silent! let g:plugs['fzf'].commit = 'daa602422dc272cbec6b99bc7520262672ad7230'
silent! let g:plugs['fzf.vim'].commit = '71b0e0fb94f4cd5102fb0ece4fdccf2a97649367'
silent! let g:plugs['godbolt.nvim'].commit = '09b78f294ea26af678a9ac363b7d5ce8e20b696e'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['lualine.nvim'].commit = '0a5a66803c7407767b799067986b4dc3036e1983'
silent! let g:plugs['nerdtree'].commit = 'fbb71fcd90602e3ec77f40b864b5f9b437c496c5'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['none-ls-extras.nvim'].commit = '336e84b9e43c0effb735b08798ffac382920053b'
silent! let g:plugs['none-ls.nvim'].commit = '37671797d6e5f9bd0ee3ab965ab2e6de251e1930'
silent! let g:plugs['nvim-autopairs'].commit = 'c15de7e7981f1111642e7e53799e1211d4606cb9'
silent! let g:plugs['nvim-cmp'].commit = '5260e5e8ecadaf13e6b82cf867a909f54e15fd07'
silent! let g:plugs['nvim-echo-diagnostics'].commit = 'a8f82151b1789e532253f4a6155dd2dac4653a81'
silent! let g:plugs['nvim-lspconfig'].commit = '6d2ae9fdc3111a6e8fd5db2467aca11737195a30'
silent! let g:plugs['nvim-treesitter'].commit = 'd184407e33084f4a57302bc1adf991997ccdd1da'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['plenary.nvim'].commit = 'b5c8de02a44ffeabff678090edd6a132ff8ab77d'
silent! let g:plugs['sig-window-nvim'].commit = '606e9dbd1f80646c8d2d1b4384872ec718ddc48a'
silent! let g:plugs['targets.vim'].commit = '642d3a4ce306264b05ea3219920b13ea80931767'
silent! let g:plugs['vim-cppman'].commit = '1fe11060f5bfc72d20f2c928dd3c06a309db50fc'
silent! let g:plugs['vim-fugitive'].commit = '4f59455d2388e113bd510e85b310d15b9228ca0d'
silent! let g:plugs['vim-macroeditor'].commit = '25fd58a712f58ed16ebe924c4f92c9999e455e95'
silent! let g:plugs['vim-signify'].commit = '8670143f9e12ed1cd3c9b2c54f345cdd9a4baac3'
silent! let g:plugs['vim-skip'].commit = '891a7af8d16fea5a1aa3aed55414686c01820673'
silent! let g:plugs['vim-visual-multi'].commit = 'b84a6d42c1c10678928b0bf8327f378c8bc8af5a'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['zoomwintab.vim'].commit = '3b76f740534ecc4114bc8a207ecb0db77b2fb002'

PlugUpdate!

